### ISSUE TITLE
Error running multi-environment 

### ISSUE THREAD

**Issue by Nesse** [dockware/proxy#1]
I can't start the proxy container. The container stops with this error:

```shell
_____   ____   _____ _  ____          __     _____  ______ 
|  __ \ / __ \ / ____| |/ /\ \        / /\   |  __ \|  ____|
| |  | | |  | | |    | ' /  \ \  /\  / /  \  | |__) | |__   
| |  | | |  | | |    |  <    \ \/  \/ / /\ \ |  _  /|  __|  
| |__| | |__| | |____| . \    \  /\  / ____ \| | \ \| |____ 
|_____/ \____/ \_____|_|\_\    \/  \/_/    \_\_|  \_\______|
68 69 20 64 65 76 65 6C 6F 70 65 72 2C 20 6E 69 63 65 20 74 6F 20 6D 65 65 74 20 79 6F 75
6c 6f 6f 6b 69 6e 67 20 66 6f 72 20 61 20 6a 6f 62 3f 20 77 72 69 74 65 20 75 73 20 61 74 20 6a 6f 62 73 40 64 61 73 69 73 74 77 65 62 2e 64 65
*******************************************************
** DOCKWARE IMAGE: proxy
** Tag: latest
** Version: 1.0
** Built: Mon Jan 10 08:46:28 UTC 2022
** Copyright 2022 dasistweb GmbH
*******************************************************
launching dockware...please wait...
2023/09/22 06:37:33 [emerg] 9#9: host not found in upstream "shop1" in /etc/nginx/conf.d/shop-1.conf:16
nginx: [emerg] host not found in upstream "shop1" in /etc/nginx/conf.d/shop-1.conf:16
``` 
This is my docker-compose file:

```
version: "3.8"

services:

  proxy:
    container_name: proxy
    image: dockware/proxy:latest
    ports:
      - "80:80"
      - "443:443"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    depends_on:
      - shop1
      - shop2
    volumes:
      - "./proxy/shop-1.conf:/etc/nginx/conf.d/shop-1.conf"
      - "./proxy/shop-2.conf:/etc/nginx/conf.d/shop-2.conf"
  
# -----------------------------------------------------------------------
  
  shop1:
    image: dockware/essentials:latest
    container_name: shop1
    ports:
      - "2001:22"
      - "3001:3306"
    volumes:
      - "shop_volume:/var/www/html"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1

  shop2:
    image: dockware/essentials:latest
    container_name: shop2
    ports:
      - "2002:22"
      - "3002:3306"
    volumes:
      - "shop_volume:/var/www/html"
    networks:
      - web
    environment:
      - PHP_VERSION:8.1
      - XDEBUG_ENABLED=1

# -----------------------------------------------------------------------

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false
``` 

Is there something I'm doing wrong?
